import type { HomeCourse, HomeReviewSlide } from "@/types/home"

export const homeCourseCategories: string[] = ["Featured", "Salsa", "Zumba", "Babies", "Social Programs"]

export const homeCourses: HomeCourse[] = [
  {
    id: "salsa-nocturna",
    title: "Salsa (Evening program)",
    teacher: "Mariano & Elvira",
    image: "/images/carousel/_DSC1076.JPG",
    students: "10-30 per class",
    duration: "55 min",
    badge: "Drop-in $20 / $15 new",
    category: "Salsa",
    size: "lg",
    description: "Mon/Fri 9:10pm, Tue/Thu 8:10pm, Sun 5:00pm. In-person classes.",
    slug: "salsa-nocturno",
    previewVideo: "/videos/NightProgram.mp4",
  },
  {
    id: "salsa-femenina-am",
    title: "Salsa feminine style (morning)",
    teacher: "Elvira",
    image: "/images/LadiesStyles.png",
    students: "5-10 per class",
    duration: "55 min",
    badge: "Morning",
    category: "Salsa",
    size: "md",
    description: "Mon/Wed/Thu 11:00am. Feminine styling, arms and flow.",
    slug: "salsa-femenina-matutina",
    previewVideo: "/videos/LadyStyling.mp4",
  },
  {
    id: "zumba-am",
    title: "Zumba (Morning program)",
    teacher: "Elvira",
    image: "/images/Zumba.png",
    students: "5-10 per class",
    duration: "55 min",
    badge: "Morning",
    category: "Zumba",
    size: "md",
    description: "Mon/Wed/Thu 10:00am. Latin cardio to start the day.",
    slug: "zumba-matutino",
    previewVideo: "/videos/Zumba.mp4",
  },
  {
    id: "bebes-musica",
    title: "Musical stimulation for babies",
    teacher: "Omer (Tuesday) / Manuela (Friday)",
    image: "/images/Kids/Artboard 1.jpg",
    students: "12 spots (with reservation)",
    duration: "55 min",
    badge: "Limited spots",
    category: "Babies",
    size: "lg",
    description: "Tue & Fri 10am (6-18m) and 11am (18-36m).",
    slug: "musica-bebes",
    previewVideo: "/videos/Kids.mp4",
  },
  {
    id: "programas-asilos",
    title: "Programs for nursing homes",
    teacher: "PLI Team",
    image: "/images/social-program/Background.jpg",
    students: "Coming soon",
    duration: "55 min",
    badge: "Coming soon",
    category: "Social Programs",
    size: "md",
    description: "Salsa and Zumba adapted for senior residences.",
    slug: "programas-asilos",
    previewVideo: "/videos/DayCare.mp4",
  },
  {
    id: "programas-discapacidad",
    title: "Programs for care centers",
    teacher: "PLI Team",
    image: "/images/social-program/Background-1.jpg",
    students: "Coming soon",
    duration: "55 min",
    badge: "Coming soon",
    category: "Social Programs",
    size: "md",
    description: "Inclusive Salsa, Zumba and more for specialized care centers.",
    slug: "programas-discapacidad",
    previewVideo: "/videos/DayCare.mp4",
  },
]

export const homeReviewSlides: HomeReviewSlide[] = [
  {
    image: "/images/carousel/_DSC1079.JPG",
    text: "The instructors break down every move so clearly. I improved my timing and confidence in just a few classes!",
    author: "Julia M.",
    role: "Beginner to Intermediate",
  },
  {
    image: "/images/carousel/_DSC1087.JPG",
    text: "Amazing community vibe. Practice nights are the highlight of my week and helped me level up fast.",
    author: "Carlos R.",
    role: "On2 Enthusiast",
  },
  {
    image: "/images/carousel/_DSC1076.JPG",
    text: "Professional teaching with a friendly atmosphere. The video reviews after class are a game changer.",
    author: "Stephanie K.",
    role: "Advanced Dancer",
  },
]
