import type React from "react"

import type { StepEnabledContext } from "@/components/front/staff/school"
import type { StaffRole } from "@/lib/security/staff-role"

import type StaffSchoolWorkspacePanel from "./StaffSchoolWorkspacePanel"
import type { useStaffCoursesAdmin } from "./useStaffCoursesAdmin"
import type { useStaffCourseLinksAdmin } from "./useStaffCourseLinksAdmin"
import type { useStaffRoomsAdmin } from "./useStaffRoomsAdmin"
import type { useStaffSchoolCatalogAdmin } from "./useStaffSchoolCatalogAdmin"
import type { AssignmentCourseOption, CourseLinkRow } from "./staffAdminTypes"

type StaffSchoolWorkspaceProps = React.ComponentProps<typeof StaffSchoolWorkspacePanel>

type BuildStaffSchoolWorkspacePropsInput = {
  isSchoolView: boolean
  schoolWizard: StaffSchoolWorkspaceProps["wizard"]
  wizardEnabledCtx: StepEnabledContext
  schoolCatalogAdmin: ReturnType<typeof useStaffSchoolCatalogAdmin>
  coursesAdmin: ReturnType<typeof useStaffCoursesAdmin>
  roomsAdmin: ReturnType<typeof useStaffRoomsAdmin>
  courseLinksAdmin: ReturnType<typeof useStaffCourseLinksAdmin>
  currentRole: StaffRole
  courseOptions: AssignmentCourseOption[]
  reviewPreviewHover: "home" | "single" | null
  setReviewPreviewHover: React.Dispatch<React.SetStateAction<"home" | "single" | null>>
  saveCourseLink: (event: React.FormEvent) => void
  deleteCourseLink: (linkId: string) => void
  toggleCourseLinkActive: (link: CourseLinkRow) => void
  formatDateTime: (value: string | number | null | undefined) => string
  formatClockLabel: (value: string) => string
  formatMoney: (amount: number, currency?: string) => string
  formatUsdInputLabel: (value: string) => string
  centsToUsdInput: (value: number | null | undefined) => string
}

export function buildStaffSchoolWorkspaceProps({
  isSchoolView,
  schoolWizard,
  wizardEnabledCtx,
  schoolCatalogAdmin,
  coursesAdmin,
  roomsAdmin,
  courseLinksAdmin,
  currentRole,
  courseOptions,
  reviewPreviewHover,
  setReviewPreviewHover,
  saveCourseLink,
  deleteCourseLink,
  toggleCourseLinkActive,
  formatDateTime,
  formatClockLabel,
  formatMoney,
  formatUsdInputLabel,
  centsToUsdInput,
}: BuildStaffSchoolWorkspacePropsInput): StaffSchoolWorkspaceProps {
  const {
    schoolLoading,
    schoolBusy,
    schoolError,
    schoolSuccess,
    schoolCourses,
    schoolRooms,
    packageStatusFilter,
    packageSearchQuery,
    editingPackageId,
    schoolPointsRules,
    packageForm,
    pointsRuleForm,
    pointsAssignForm,
    filteredSchoolPackages,
    packageCounts,
    selectedPointsRuleTemplate,
    setPackageStatusFilter,
    setPackageSearchQuery,
    setEditingPackageId,
    setPackageForm,
    setPointsRuleForm,
    setPointsAssignForm,
    fetchSchoolData,
    togglePackageCourse,
    savePackagePlan,
    setPackageLifecycleState,
    deletePackagePlan,
    savePointsRule,
    assignPointsManually,
    resetPointsRuleForm,
    resetPointsAssignForm,
  } = schoolCatalogAdmin

  const {
    courseForm,
    setCourseForm,
    courseScheduleDate,
    setCourseScheduleDate,
    courseScheduleDates,
    setCourseScheduleDates,
    courseRecurringWeekdays,
    courseMirrorEnabled,
    setCourseMirrorEnabled,
    courseMirrorWeekdays,
    setCourseMirrorWeekdays,
    courseRepeatAllMonth,
    setCourseRepeatAllMonth,
    courseRecurrenceMode,
    setCourseRecurrenceMode,
    courseRecurrenceEndsAt,
    setCourseRecurrenceEndsAt,
    courseScheduleTime,
    setCourseScheduleTime,
    courseScheduleSlots,
    quickScheduleTimes,
    editingQuickTimeIndex,
    quickTimeDraft,
    setQuickTimeDraft,
    setEditingQuickTimeIndex,
    scheduleTimePickerOpen,
    setScheduleTimePickerOpen,
    courseLocalImageName,
    courseLocalVideoName,
    courseMediaUploading,
    courseEditingSlug,
    courseCatalogSearch,
    setCourseCatalogSearch,
    courseCatalogFilter,
    setCourseCatalogFilter,
    courseSlugConflict,
    courseImageInputRef,
    courseVideoInputRef,
    scheduleTimePickerRef,
    courseFormFieldsRef,
    isSpecialEventCourse,
    scheduleDerivedData,
    scheduleCalendarMap,
    previewMediaUrl,
    isEmbedPreviewVideo,
    previewVideoSource,
    selectedCourseKindLabel,
    selectedCourseKindReviewLabel,
    courseReviewVariants,
    previewEditorHref,
    previewPublicHref,
    regularScheduleWarningMessage,
    scheduleSlotTimeUsage,
    scheduleTimeCourseUsage,
    scheduleTimeOptions,
    resetCourseBuilder,
    saveCourseCatalog,
    getCourseScheduleDateTooltip,
    getCourseScheduleDateTone,
    copyCourseLink,
    shareCourse,
    handleUseSlugSuggestion,
    handleEditExistingCourse,
    addCourseScheduleSlot,
    removeCourseScheduleSlot,
    toggleCourseRecurringWeekday,
    toggleCourseMirrorWeekday,
    handleCourseLocalImage,
    handleCourseLocalVideo,
    loadCourseIntoForm,
    deleteCourse,
    toggleCourseActive,
    startEditingQuickTime,
    commitQuickTimeEdit,
  } = coursesAdmin

  const {
    roomForm,
    roomSearchQuery,
    roomStatusFilter,
    roomSaving,
    roomBusyId,
    roomFormError,
    roomFormSuccess,
    roomActionErrors,
    roomReservationForm,
    roomReservationSaving,
    roomReservationBusyId,
    roomReservationFormError,
    roomReservationFormSuccess,
    roomById,
    activeRoomOptions,
    courseRoomOptions,
    visibleRooms,
    currentUpcomingReservations,
    reservationAssignableStaff,
    reservationStaffLabelById,
    reservationRangePreview,
    setRoomSearchQuery,
    setRoomStatusFilter,
    resetRoomForm,
    updateRoomFormField,
    loadRoomIntoForm,
    saveRoom,
    disableRoom,
    activateRoom,
    openRoomSafeDeleteModal,
    openRoomReassignModal,
    updateRoomReservationFormField,
    updateRoomReservationDateRange,
    saveRoomReservation,
    openRoomReservationCancelModal,
    formatReservationDateLabel,
    resolveRoomDisableActionState,
  } = roomsAdmin

  const {
    courseLinksAsA,
    courseLinksAsB,
    courseLinkForm,
    courseLinkEditingId,
    courseLinkSaving,
    courseLinkError,
    courseLinkSuccess,
    courseLinkStats,
    allCourseLinksMap,
    setCourseLinkForm,
    resetCourseLinkForm,
    editCourseLink,
  } = courseLinksAdmin

  return {
    isSchoolView,
    wizard: schoolWizard,
    wizardEnabledContext: wizardEnabledCtx,
    catalog: {
      schoolLoading,
      fetchSchoolData: () => void fetchSchoolData({ showLoader: true }),
      schoolCoursesCount: schoolCourses.length,
      activeSchoolCoursesCount: schoolCourses.filter((course) => course.active).length,
      schoolRoomsCount: schoolRooms.length,
      activeRoomOptionsCount: activeRoomOptions.length,
      packageCounts,
      schoolPointsRulesCount: schoolPointsRules.length,
      activeSchoolPointsRulesCount: schoolPointsRules.filter((rule) => rule.active).length,
      courseLinkStats,
    },
    status: { schoolBusy, schoolError, schoolSuccess },
    requestWizardSave: () => {
      if (schoolWizard.activeEntity === "courses") {
        const form = document.querySelector<HTMLFormElement>("[data-wizard-form='courses']")
        form?.requestSubmit()
      } else if (schoolWizard.activeEntity === "packages") {
        const form = document.querySelector<HTMLFormElement>("[data-wizard-form='packages']")
        form?.requestSubmit()
      }
    },
    reservations: {
      visible: schoolWizard.activeEntity === "rooms" && schoolWizard.step === 1,
      wizard: {
        step: schoolWizard.step,
        totalSteps: schoolWizard.totalSteps,
        onPrevious: () => schoolWizard.prevStep(wizardEnabledCtx),
        onNext: () => schoolWizard.nextStep(wizardEnabledCtx),
      },
      form: {
        roomReservationForm,
        reservationRangePreview,
        roomReservationFormError,
        roomReservationFormSuccess,
        roomReservationSaving,
        activeRoomOptions,
        reservationAssignableStaff,
        onDateRangeChange: updateRoomReservationDateRange,
        onFieldChange: updateRoomReservationFormField,
        onSubmit: saveRoomReservation,
        formatReservationDateLabel,
      },
      list: {
        schoolLoading,
        reservations: currentUpcomingReservations,
        roomById,
        roomReservationBusyId,
        onCancel: openRoomReservationCancelModal,
        formatDateTime,
        resolveAssignedStaffLabel: (staffId) => {
          if (!staffId) return "Unassigned"
          return reservationStaffLabelById[staffId] || staffId
        },
      },
    },
    rooms: {
      visible: schoolWizard.activeEntity === "rooms" && schoolWizard.step === 0,
      wizard: {
        step: schoolWizard.step,
        totalSteps: schoolWizard.totalSteps,
        onPrevious: () => schoolWizard.prevStep(wizardEnabledCtx),
        onNext: () => schoolWizard.nextStep(wizardEnabledCtx),
      },
      form: { roomForm, updateRoomFormField, onSaveRoom: saveRoom, resetRoomForm, roomSaving, roomFormError, roomFormSuccess },
      filters: { roomSearchQuery, setRoomSearchQuery, roomStatusFilter, setRoomStatusFilter },
      data: { schoolLoading, visibleRooms, activeRoomOptions, roomBusyId, roomActionErrors },
      actions: { loadRoomIntoForm, activateRoom, disableRoom, openRoomReassignModal, openRoomSafeDeleteModal, resolveRoomDisableActionState },
    },
    courseStudio: {
      wizard: {
        activeEntity: schoolWizard.activeEntity,
        step: schoolWizard.step,
        totalSteps: schoolWizard.totalSteps,
        enabledContext: wizardEnabledCtx,
        onPrevious: schoolWizard.prevStep,
        onNext: schoolWizard.nextStep,
      },
      form: { onSubmit: saveCourseCatalog, courseImageInputRef, courseVideoInputRef, courseFormFieldsRef, onLocalImageChange: handleCourseLocalImage, onLocalVideoChange: handleCourseLocalVideo },
      isSpecialEventCourse,
      mainInfo: { courseForm, setCourseForm, courseSlugConflict, courseRoomOptions, roomById, onUseSlugSuggestion: handleUseSlugSuggestion, onEditExistingCourse: handleEditExistingCourse },
      pricing: { courseEditingSlug, courseForm, setCourseForm },
      media: { courseEditingSlug, courseForm, setCourseForm, courseMediaUploading, courseLocalVideoName, courseLocalImageName },
      schedule: {
        schoolLoading,
        courseForm,
        setCourseForm,
        courseRecurringWeekdays,
        toggleCourseRecurringWeekday,
        courseMirrorEnabled,
        setCourseMirrorEnabled,
        courseMirrorWeekdays,
        setCourseMirrorWeekdays,
        toggleCourseMirrorWeekday,
        courseScheduleDate,
        setCourseScheduleDate,
        courseScheduleDates,
        setCourseScheduleDates,
        quickScheduleTimes,
        editingQuickTimeIndex,
        quickTimeDraft,
        setQuickTimeDraft,
        setEditingQuickTimeIndex,
        startEditingQuickTime,
        commitQuickTimeEdit,
        courseScheduleTime,
        setCourseScheduleTime,
        scheduleTimePickerOpen,
        setScheduleTimePickerOpen,
        scheduleTimePickerRef,
        scheduleTimeOptions,
        scheduleSlotTimeUsage,
        scheduleTimeCourseUsage,
        addCourseScheduleSlot,
        removeCourseScheduleSlot,
        courseScheduleSlots,
        regularScheduleWarningMessage,
        courseRepeatAllMonth,
        setCourseRepeatAllMonth,
        courseRecurrenceMode,
        setCourseRecurrenceMode,
        courseRecurrenceEndsAt,
        setCourseRecurrenceEndsAt,
      },
      links: {
        courseEditingSlug,
        schoolCourses,
        courseLinkError,
        courseLinkSuccess,
        courseLinkForm,
        setCourseLinkForm,
        courseLinkSaving,
        courseLinkEditingId,
        courseLinksAsA,
        courseLinksAsB,
        onSaveCourseLink: saveCourseLink,
        onResetCourseLinkForm: resetCourseLinkForm,
        onToggleCourseLinkActive: toggleCourseLinkActive,
        onEditCourseLink: editCourseLink,
        onDeleteCourseLink: deleteCourseLink,
        formatUsdInputLabel,
        centsToUsdInput,
      },
      preview: {
        schoolLoading,
        courseForm,
        selectedCourseKindLabel,
        selectedCourseKindReviewLabel,
        courseReviewVariants,
        reviewPreviewHover,
        setReviewPreviewHover,
        previewVideoSource,
        isEmbedPreviewVideo,
        previewMediaUrl,
        previewEditorHref,
        defaultRoomName: courseForm.defaultRoomId ? roomById[courseForm.defaultRoomId]?.name || "Selected room" : "None",
        scheduleTimes: scheduleDerivedData.times,
        scheduleCalendarValues: [...scheduleCalendarMap.keys()].sort(),
        formatUsdInputLabel,
        formatClockLabel,
        getCourseScheduleDateTooltip,
        getCourseScheduleDateTone,
      },
      publish: { courseEditingSlug, previewPublicHref, schoolBusy, courseMediaUploading, onCopyCourseLink: () => void copyCourseLink(), onShareCourse: shareCourse, onResetCourseBuilder: resetCourseBuilder },
    },
    courseCatalog: {
      visible: schoolWizard.activeEntity === "courses",
      schoolLoading,
      schoolCourses,
      courseCatalogSearch,
      setCourseCatalogSearch,
      courseCatalogFilter,
      setCourseCatalogFilter,
      allCourseLinksMap,
      schoolBusy,
      currentRole,
      onEditCourse: loadCourseIntoForm,
      onToggleCourseActive: toggleCourseActive,
      onDeleteCourse: deleteCourse,
    },
    packagesPoints: {
      wizard: {
        activeEntity: schoolWizard.activeEntity,
        step: schoolWizard.step,
        totalSteps: schoolWizard.totalSteps,
        onPrevious: () => schoolWizard.prevStep(wizardEnabledCtx),
        onNext: () => schoolWizard.nextStep(wizardEnabledCtx),
      },
      schoolLoading,
      schoolBusy,
      currentRole,
      packages: {
        form: packageForm,
        setForm: setPackageForm,
        editingPackageId,
        setEditingPackageId,
        courseOptions,
        togglePackageCourse,
        onSave: savePackagePlan,
        statusFilter: packageStatusFilter,
        setStatusFilter: setPackageStatusFilter,
        searchQuery: packageSearchQuery,
        setSearchQuery: setPackageSearchQuery,
        counts: packageCounts,
        filteredItems: filteredSchoolPackages,
        setLifecycleState: setPackageLifecycleState,
        deletePackagePlan,
        formatMoney,
      },
      points: {
        ruleForm: pointsRuleForm,
        setRuleForm: setPointsRuleForm,
        selectedTemplate: selectedPointsRuleTemplate,
        onSaveRule: savePointsRule,
        resetRuleForm: resetPointsRuleForm,
        assignForm: pointsAssignForm,
        setAssignForm: setPointsAssignForm,
        onAssign: assignPointsManually,
        resetAssignForm: resetPointsAssignForm,
        rules: schoolPointsRules,
      },
    },
  }
}
