/**
 * Generates the maintenance-window freeze checklist for the Clerk prod
 * instance migration (see design's "Lazy-create audit" and the operator
 * runbook's Maintenance Window Entry step).
 *
 * MANDATORY per judgment-day carry-over #2: the freeze list must be
 * GENERATED by grepping call sites of the create-capable Clerk functions,
 * not hand-maintained. Re-run this script at cutover time — do not trust a
 * stale copy embedded in the runbook.
 *
 * Usage: npx tsx scripts/generate-clerk-freeze-list.ts
 */
import { execFileSync } from "node:child_process"
import path from "node:path"

// The three create-capable Clerk call sites from the design's Lazy-create
// audit — any route reaching one of these during the swap→remap gap can
// create a Clerk user or StaffAccount row that the pre-built migration map
// does not cover.
export const FREEZE_SYMBOLS = ["syncStaffAccountFromClerkUser", "ensureClerkUser", "client.invitations.createInvitation"] as const

export type FreezeSymbol = (typeof FREEZE_SYMBOLS)[number]

export type CallSite = { symbol: FreezeSymbol; file: string; line: number; snippet: string }

export type RouteFinding = { routeFile: string; via: Array<{ symbol: string; sourceFile: string }> }

/**
 * Grep execution seam — injected so the resolution logic below can be unit
 * tested without shelling out against the real repo tree.
 */
export type GrepRunner = {
  /** grep -rn -F <needle> <dirs> — returns raw stdout lines "file:line:snippet", or [] if no matches. */
  grepLines(needle: string, dirs: string[]): string[]
  /** grep -rl -F <needle> <dir> — returns matching file paths, or [] if no matches. */
  grepFiles(needle: string, dir: string): string[]
}

export const createRealGrepRunner = (repoRoot: string): GrepRunner => ({
  grepLines(needle, dirs) {
    try {
      const output = execFileSync("grep", ["-rn", "--include=*.ts", "--include=*.tsx", "-F", needle, ...dirs], {
        cwd: repoRoot,
        encoding: "utf8",
      })
      return output.split("\n").filter(Boolean)
    } catch (error) {
      const execError = error as { status?: number }
      if (execError.status === 1) return []
      throw error
    }
  },
  grepFiles(needle, dir) {
    try {
      const output = execFileSync("grep", ["-rl", "--include=*.ts", "--include=*.tsx", "-F", needle, dir], {
        cwd: repoRoot,
        encoding: "utf8",
      })
      return output.split("\n").filter(Boolean)
    } catch (error) {
      const execError = error as { status?: number }
      if (execError.status === 1) return []
      throw error
    }
  },
})

const isApiRoute = (file: string): boolean => file.startsWith("app/api/") && (file.endsWith("/route.ts") || file.endsWith("/route.tsx"))

const parseGrepLine = (symbol: FreezeSymbol, line: string): CallSite | null => {
  const match = line.match(/^([^:]+):(\d+):(.*)$/)
  if (!match) return null
  const [, file, lineNum, snippet] = match
  return { symbol, file, line: Number(lineNum), snippet: snippet.trim() }
}

const escapeForRegex = (value: string): string => value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")

/**
 * True when the snippet is the symbol's OWN declaration/export line (e.g.
 * `export const syncStaffAccountFromClerkUser = async (...)`), not a call
 * site that merely starts with `const`/`function` (e.g. `const account =
 * await syncStaffAccountFromClerkUser(...)`). Only the former should be
 * excluded — the symbol name must appear immediately after the
 * declaration keyword.
 */
const isOwnDeclarationLine = (symbol: string, snippet: string): boolean => {
  const declarationPattern = new RegExp(`^(export\\s+)?(async\\s+)?(function|const)\\s+${escapeForRegex(symbol)}\\b`)
  return declarationPattern.test(snippet)
}

const findCallSites = (grep: GrepRunner, symbol: FreezeSymbol): CallSite[] => {
  return grep
    .grepLines(symbol, ["app", "lib"])
    .map((line) => parseGrepLine(symbol, line))
    .filter((row): row is CallSite => row !== null)
    // Exclude test fixtures and the symbol's own declaration/export line —
    // we only want CALL sites, not definitions or test files.
    .filter((row) => !row.file.startsWith("tests/"))
    .filter((row) => !isOwnDeclarationLine(row.symbol, row.snippet))
}

/**
 * Resolves a non-route source file (e.g. a lib/*.ts helper) to the set of
 * app/api/** route files that import it, one hop. This mirrors the design's
 * Lazy-create audit, which manually traced `lib/checkout.ts` back to the
 * checkout routes and `lib/clerk-users.ts` back to its direct route callers.
 */
const findRouteImportersOf = (grep: GrepRunner, libFile: string): string[] => {
  const withoutExt = libFile.replace(/\.tsx?$/, "")
  const specifier = `@/${withoutExt}`
  return grep.grepFiles(specifier, "app/api").filter(isApiRoute)
}

export const generateFreezeList = (grep: GrepRunner): RouteFinding[] => {
  const allCallSites = FREEZE_SYMBOLS.flatMap((symbol) => findCallSites(grep, symbol))

  const routeFindings = new Map<string, RouteFinding>()

  const addFinding = (routeFile: string, symbol: string, sourceFile: string) => {
    const existing = routeFindings.get(routeFile)
    if (existing) {
      if (!existing.via.some((v) => v.symbol === symbol && v.sourceFile === sourceFile)) {
        existing.via.push({ symbol, sourceFile })
      }
      return
    }
    routeFindings.set(routeFile, { routeFile, via: [{ symbol, sourceFile }] })
  }

  for (const callSite of allCallSites) {
    if (isApiRoute(callSite.file)) {
      addFinding(callSite.file, callSite.symbol, callSite.file)
      continue
    }

    // Non-route file (e.g. lib/checkout.ts, lib/security/staff-account-sync.ts,
    // app/staff/resolve/page.tsx) — resolve one hop to its route importers.
    if (callSite.file.startsWith("lib/")) {
      const routeImporters = findRouteImportersOf(grep, callSite.file)
      for (const routeFile of routeImporters) {
        addFinding(routeFile, callSite.symbol, callSite.file)
      }
    }
  }

  return Array.from(routeFindings.values()).sort((a, b) => a.routeFile.localeCompare(b.routeFile))
}

export const formatFreezeChecklist = (findings: RouteFinding[], generatedAt: Date): string => {
  const today = generatedAt.toISOString().slice(0, 10)
  const lines: string[] = []
  lines.push(`# Clerk migration freeze checklist — generated ${today}`)
  lines.push(`# REGENERATE at cutover time: npx tsx scripts/generate-clerk-freeze-list.ts`)
  lines.push("")
  lines.push(`Freeze scope is defined by CAPABILITY (any route reaching a create-capable Clerk call), not by this list alone.`)
  lines.push(`This list is a reproducible STARTING POINT — verify against a fresh run before entering the maintenance window.`)
  lines.push("")

  for (const finding of findings) {
    lines.push(`- [ ] ${finding.routeFile}`)
    for (const via of finding.via) {
      const viaNote = via.sourceFile === finding.routeFile ? "" : ` (via ${via.sourceFile})`
      lines.push(`      - ${via.symbol}${viaNote}`)
    }
  }

  lines.push("")
  lines.push(`Total routes to freeze: ${findings.length}`)

  return lines.join("\n")
}

// ── main() — thin, only touches the real filesystem here ─────────────

const isDirectExecution =
  process.argv[1] === import.meta.filename || process.argv[1] === import.meta.url.replace("file://", "")

if (isDirectExecution) {
  const repoRoot = path.resolve(import.meta.dirname, "..")
  const grep = createRealGrepRunner(repoRoot)
  const findings = generateFreezeList(grep)
  console.log(formatFreezeChecklist(findings, new Date()))
}
